### ISSUE TITLE
Position tracking without PTP or camera ticks

### ISSUE THREAD

**Issue by samuelbray32** [LorenFrankLab/trodes_to_nwb#62]
Came across a non-ptp dataset where there was not a cammera tick channel for the run session camera. Checked with experimenter and confirmed it wasn't recorded at experiment time.  

Should we have an option to use the clock time from .cameraHWSync files if dio channel isn't available, or is this too sketchy?

**Comment by lfrank** [comment]
I would worry that the times are going to be quite a ways off, but I defer to @edeno as to how dangerous this would be.

On Nov 6, 2023, at 11:06 AM, Samuel Bray ***@***.***> wrote:


This Message Is From an External Sender
This message came from outside your organization.


Came across a non-ptp dataset where there was not a cammera tick channel for the run session camera. Checked with experimenter and confirmed it wasn't recorded at experiment time.

Should we have an option to use the clock time from .cameraHWSync files if dio channel isn't available, or is this too sketchy?

**Comment by edeno** [comment]
We will have poor estimation of the delay from the MCU so agreed with Loren that it is dangerous.
