### ISSUE TITLE
Unused information in the metadata.yml format

### ISSUE THREAD

**Issue by samuelbray32** [LorenFrankLab/trodes_to_nwb#76]
The metadata for electrode groups has both a `location` and `targeted_location` field. However only `targeted_location` is used in conversion (there isn't space in the pynwb electrode group object for both). Propose removing the location from the metadata to avoid confusion.

- [ ] Change example metadata files
- [ ] Change the metadata generator to remove this field
- [ ] Change the metadata validator to not require this field

**Comment by zoldello** [comment]
@samuelbray32 Please keep me updated on a final decision. A change in any of these require other things to change.
