### ISSUE TITLE
trodes_to_nwb blows up when refNTrodeID is either 0 or -1 or not set

### ISSUE THREAD

**Issue by zoldello** [LorenFrankLab/trodes_to_nwb#88]
in the trodesconf file, if refNTrodeID is -1 or 0, this line of code blows up

[https://github.com/LorenFrankLab/trodes_to_nwb/blob/main/src/trodes_to_nwb/convert_rec_header.py#L211](https://github.com/LorenFrankLab/trodes_to_nwb/blob/main/src/trodes_to_nwb/convert_rec_header.py#L211)

When refNTrodesId is not set, this line blows up
[https://github.com/LorenFrankLab/trodes_to_nwb/blob/main/src/trodes_to_nwb/convert_rec_header.py#L228](https://github.com/LorenFrankLab/trodes_to_nwb/blob/main/src/trodes_to_nwb/convert_rec_header.py#L228)

because this line is not called
[https://github.com/LorenFrankLab/trodes_to_nwb/blob/main/src/trodes_to_nwb/convert_rec_header.py#L210](https://github.com/LorenFrankLab/trodes_to_nwb/blob/main/src/trodes_to_nwb/convert_rec_header.py#L210)

**Comment by zoldello** [comment]
@samuelbray32 Normally I try to fix bugs myself. However, this bugs requires a discussion of the research-rules to determine how these state should be operated.

**Comment by samuelbray32** [comment]
Since this sets the reference that will later be used when importing to spyglass, my assumption is that it should be defined at this time and shouldn't be a nullable option.  Can ask at group meeting tomorrow as well and see what people think

**Comment by khl02007** [comment]
@samuelbray32 yes, if you used a reference channel for your recording during data acquisition, you should set it. But it's possible that you didn't set any reference channel, as in our case. So it should be possible to set this to e.g. -1.
