### ISSUE TITLE
Potential features?

### ISSUE THREAD

**Issue by zoldello** [LorenFrankLab/trodes_to_nwb#89]
I can create individual issues for each if you like. I and Kyu noticed a few things while working on a NET probe NWB data. They are related to the yml file used by trodes_to_nwb set up and how trodes_to_nwb uses it.

1. Behavioral Events: Is there any objection to having the comment field populated? This will enable users to have notes that give more details on the Behavioral Events and information for others using the data. The Description field does not suffice for this.  For example, a description of "Din1" does not explain much. The comment field in the NWB file is always empty.

2. Task Id: In Tasks -> Item -> Task Epoch, only numbers are used. But in trodes_to_nwb, in the converted NWB file, the taskId is formatted like "1_r0" (the value is altered). Is there a reason why the value was restructured.

3. Associated File: In Associated Files -> Item -> Task Epoch, the in the generated NWB file is a string, rather than a number as in Tasks -> Item -> Task Epoch. Is there a reason for this inconsistency?

**Comment by samuelbray32** [comment]
I'll look at these more and respond as I can:

1. I don't see a reason why not in principle, though I don't think it would feed to spyglass currently.  Typically, the `name` field would be where you would put things like `light_1` , `pump_2`, etc.  If you need more information than that to go in let me know and can add that

**Comment by khl02007** [comment]
@samuelbray32 
Re: 1, yes, could you please make it possible for us to specify more information in the `comments` field (even if it doesn't propagate to spyglass)? We would like to put more description about each of the Din and Dout but seems it isn't possible to do so with the `description` field at the moment

**Comment by edeno** [comment]
I think everything here has been addressed by #91 and @samuelbray32 's responses. I am closing. Feel free to open if there are more issues.
